# Generated by Django 4.1.2 on 2022-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_auto_20171128_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='gay_friendly',
        ),
        migrations.AlterField(
            model_name='sea',
            name='area',
            field=models.BigIntegerField(help_text='km&#178;', verbose_name='area'),
        ),
    ]
