# Generated by Django 4.1.2 on 2022-10-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_remove_country_gay_friendly_alter_sea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='oceans',
            field=models.ManyToManyField(blank=True, null=True, to='integration.ocean', verbose_name='oceans'),
        ),
    ]
