# Generated by Django 4.1.2 on 2022-10-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_alter_continent_oceans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocean',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='map url'),
        ),
    ]
