# Generated by Django 4.1.2 on 2022-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testingtype',
            options={'verbose_name': 'Test Type', 'verbose_name_plural': 'Test Type'},
        ),
    ]
